// Action labels whose former catalogue keys included platform-dependent glyphs.
// SVG icons now render separately, so the translated text stays glyph-free.
// Columns: en, zh-CN, ko, ja, ar, it, hi, pt (same order as catalog.generated.ts).
export const ACTION_CATALOG: string[][] = [
  ["GUI color", "界面颜色", "GUI 색상", "GUIカラー", "لون الواجهة", "Colore GUI", "GUI रंग", "Cor da GUI"],
  ["Text color", "文字颜色", "텍스트 색상", "テキストカラー", "لون النص", "Colore testo", "टेक्स्ट रंग", "Cor do texto"],
  ["Choose GUI color", "选择界面颜色", "GUI 색상 선택", "GUIカラーを選択", "اختر لون الواجهة", "Scegli il colore GUI", "GUI रंग चुनें", "Escolher cor da GUI"],
  ["Choose text color", "选择文字颜色", "텍스트 색상 선택", "テキストカラーを選択", "اختر لون النص", "Scegli il colore del testo", "टेक्स्ट रंग चुनें", "Escolher cor do texto"],
  ["GUI color palette", "界面调色板", "GUI 색상 팔레트", "GUIカラーパレット", "لوحة ألوان الواجهة", "Tavolozza colori GUI", "GUI रंग पैलेट", "Paleta de cores da GUI"],
  ["Text color palette", "文字调色板", "텍스트 색상 팔레트", "テキストカラーパレット", "لوحة ألوان النص", "Tavolozza colori testo", "टेक्स्ट रंग पैलेट", "Paleta de cores do texto"],
  ["Feed", "订阅", "피드", "フィード", "تغذية", "Feed", "फ़ीड", "Feed"],
  ["Re-feed", "重新订阅", "재피드", "再フィード", "إعادة التغذية", "Re-feed", "री-फ़ीड", "Re-feed"],
  ["Reopen", "重新打开", "다시 열기", "再度開く", "إعادة فتح", "Riapri", "फिर से खोलें", "Reabrir"],
  ["Send report", "发送报告", "보고서 전송", "レポートを送信", "إرسال التقرير", "Invia rapporto", "रिपोर्ट भेजें", "Enviar relatório"],
  ["Active", "进行中", "진행 중", "進行中", "قيد التنفيذ", "Attivi", "सक्रिय", "Ativos"],
  ["All steps done — reopen one from the Archive tab, or add a new step above.", "所有步骤完成——从存档标签页重新打开一个，或在上方添加一个新步骤。", "모든 단계가 완료되었습니다 — 보관 탭에서 하나를 다시 열거나 위에 새 단계를 추가하세요.", "すべてのステップが完了しました — アーカイブタブから1つを再開するか、上に新しいステップを追加してください。", "تمت جميع الخطوات — أعد فتح واحدة من تبويب الأرشيف، أو أضف خطوة جديدة أعلاه.", "Tutti i passaggi completati — riaprine uno dalla scheda Archivio, oppure aggiungi un nuovo passaggio sopra.", "सभी चरण पूरे हो गए — आर्काइव टैब से कोई एक फिर से खोलें, या ऊपर नया चरण जोड़ें।", "Todos os passos concluídos — reabra um na aba Arquivo ou adicione um novo passo acima."],
  ["No archived steps yet — steps marked done move here.", "尚无已存档的步骤——标记为完成的步骤会移到这里。", "아직 보관된 단계가 없습니다 — 완료로 표시된 단계가 여기로 이동합니다.", "アーカイブされたステップはまだありません — 完了にしたステップはここに移動します。", "لا توجد خطوات مؤرشفة بعد — تنتقل الخطوات المكتملة إلى هنا.", "Nessun passaggio archiviato — i passaggi contrassegnati come completati vengono spostati qui.", "अभी कोई आर्काइव किया गया चरण नहीं — पूर्ण चिह्नित चरण यहाँ आ जाते हैं।", "Nenhum passo arquivado ainda — passos marcados como concluídos vêm para cá."],
  ["No steps yet — add one above, or digest your notes below.", "尚无步骤 — 在上方添加一个，或在下方消化您的笔记。", "아직 단계가 없습니다 — 위에서 추가하거나, 아래에서 메모를 요약하세요.", "まだステップはありません — 上に追加するか、下のメモを処理してください。", "لا توجد خطوات بعد — أضف واحدة أعلاه، أو عالج ملاحظاتك أدناه.", "Nessun passaggio ancora — aggiungine uno sopra, o elabora le tue note qui sotto.", "अभी कोई चरण नहीं — ऊपर एक जोड़ें, या नीचे अपने नोट्स डाइजेस्ट करें।", "Nenhum passo ainda — adicione um acima ou processe suas notas abaixo."],
  ["Chat text size", "聊天文字大小", "채팅 글자 크기", "チャット文字サイズ", "حجم نص الدردشة", "Dimensione testo chat", "चैट टेक्स्ट आकार", "Tamanho do texto do chat"],
  ["Increase chat text size", "增大聊天文字", "채팅 글자 크게", "チャット文字を大きく", "تكبير نص الدردشة", "Aumenta dimensione testo chat", "चैट टेक्स्ट बड़ा करें", "Aumentar texto do chat"],
  ["Decrease chat text size", "减小聊天文字", "채팅 글자 작게", "チャット文字を小さく", "تصغير نص الدردشة", "Riduci dimensione testo chat", "चैट टेक्स्ट छोटा करें", "Diminuir texto do chat"],
  ["Fix with agent", "让智能体修复", "에이전트로 수정", "エージェントで修正", "إصلاح بواسطة الوكيل", "Correggi con l'agente", "एजेंट से ठीक करें", "Corrigir com o agente"],
  ["Send these failures to the coder agent to diagnose and fix", "将这些失败发送给编码智能体进行诊断和修复", "이 실패를 코더 에이전트에게 보내 진단하고 수정하게 합니다", "これらの失敗をコーダーエージェントに送信して診断・修正します", "أرسل هذه الإخفاقات إلى وكيل البرمجة لتشخيصها وإصلاحها", "Invia questi errori all'agente coder per diagnosticarli e correggerli", "इन विफलताओं को निदान और सुधार के लिए कोडर एजेंट को भेजें", "Enviar essas falhas ao agente coder para diagnosticar e corrigir"],
  ["Sent to the coder agent — watch the chat for the fix.", "已发送给编码智能体——请在聊天中查看修复进展。", "코더 에이전트에게 전송되었습니다 — 채팅에서 수정 내용을 확인하세요.", "コーダーエージェントに送信しました — チャットで修正を確認してください。", "تم الإرسال إلى وكيل البرمجة — تابع الدردشة لمشاهدة الإصلاح.", "Inviato all'agente coder — segui la chat per la correzione.", "कोडर एजेंट को भेज दिया गया — सुधार के लिए चैट देखें।", "Enviado ao agente coder — acompanhe o chat para ver a correção."],
  ["Coder is mid-run — the fix task is queued as a ⚡ steer and will run next.", "编码智能体正在运行——修复任务已加入 ⚡ 引导队列，稍后将执行。", "코더가 실행 중입니다 — 수정 작업이 ⚡ 스티어로 대기열에 추가되어 곧 실행됩니다.", "コーダーは実行中です — 修正タスクは ⚡ ステアとしてキューに入り、次に実行されます。", "الوكيل قيد التشغيل — تمت جدولة مهمة الإصلاح كتوجيه ⚡ وستُنفذ تاليًا.", "Il coder è in esecuzione — il task di correzione è in coda come ⚡ steer e partirà a breve.", "कोडर अभी रन में है — सुधार कार्य ⚡ स्टीयर के रूप में कतार में है और अगला चलेगा।", "O coder está em execução — a tarefa de correção entrou na fila como ⚡ steer e será executada em seguida."],
  ["Can't start the fix — no model is selected in the Coder pane. Pick a model above the chat, then press 🛠 Fix with agent again.", "无法开始修复——编码窗格未选择模型。请在聊天上方选择一个模型，然后再次按 🛠 让智能体修复。", "수정을 시작할 수 없습니다 — 코더 창에 모델이 선택되어 있지 않습니다. 채팅 위에서 모델을 선택한 후 🛠 에이전트로 수정을 다시 누르세요.", "修正を開始できません — コーダーペインでモデルが選択されていません。チャット上部でモデルを選び、もう一度 🛠 エージェントで修正を押してください。", "تعذر بدء الإصلاح — لم يتم اختيار نموذج في لوحة المبرمج. اختر نموذجًا أعلى الدردشة ثم اضغط 🛠 إصلاح بواسطة الوكيل مرة أخرى.", "Impossibile avviare la correzione — nessun modello selezionato nel pannello Coder. Scegli un modello sopra la chat, poi premi di nuovo 🛠 Correggi con l'agente.", "सुधार शुरू नहीं हो सकता — कोडर पैन में कोई मॉडल चुना नहीं गया है। चैट के ऊपर एक मॉडल चुनें, फिर 🛠 एजेंट से ठीक करें दोबारा दबाएँ।", "Não foi possível iniciar a correção — nenhum modelo selecionado no painel do Coder. Escolha um modelo acima do chat e pressione 🛠 Corrigir com o agente novamente."],
  ["Can't start the fix — no workspace is connected on this page.", "无法开始修复——此页面未连接工作区。", "수정을 시작할 수 없습니다 — 이 페이지에 연결된 워크스페이스가 없습니다.", "修正を開始できません — このページにワークスペースが接続されていません。", "تعذر بدء الإصلاح — لا توجد مساحة عمل متصلة بهذه الصفحة.", "Impossibile avviare la correzione — nessuna area di lavoro collegata a questa pagina.", "सुधार शुरू नहीं हो सकता — इस पेज से कोई वर्कस्पेस कनेक्ट नहीं है।", "Não foi possível iniciar a correção — nenhum workspace conectado a esta página."],
];
