// Model-server lifecycle — native Rust, NO Python.
//
// Spawns llama-server.exe (LLM/runtime/llama.cpp/llama-server.exe) as
// a child process with `CREATE_NO_WINDOW` on Windows so the
// llama.cpp console never pops as a separate window. stdout + stderr
// are line-buffered and forwarded to a Tauri `server-log` event so
// the React UI can render a live log without polling.
//
// State (current child, model_id, port) lives in `ServerState` which
// the lib wires up via `tauri::Builder::manage`. Every command goes
// through the same Mutex so start/stop/status see one truth.

use crate::{models, paths};
use serde::{Deserialize, Serialize};
use std::process::Stdio;
use tauri::{AppHandle, Emitter, Manager};
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::{Child, Command};
use tokio::sync::Mutex;

#[derive(Default, Serialize, Clone)]
pub struct ServerStatus {
    pub running: bool,
    pub model_id: Option<String>,
    pub port: Option<u16>,
    pub message: String,
}

#[derive(Clone, Serialize)]
pub struct ServerLogEvent {
    pub stream: String,   // "stdout" | "stderr"
    pub line: String,
}

// ----- Network exposure (the Windows-server / remote-agents split) -----
//
// By default the model server binds 127.0.0.1 (loopback only) — nothing on
// the network can reach it. When the user explicitly enables exposure we bind
// 0.0.0.0 AND require an api-key, so remote agents (a Linux/WSL box) can use
// the model. SECURITY: 0.0.0.0 means any host that can route to this PC on
// the port can knock; the api-key gates USE (401 without it), but it's plain
// HTTP, so it's meant for a trusted LAN or (better) a VPN/SSH tunnel — never
// internet-facing. Default OFF = no change for anyone who doesn't opt in.
//
// Windows 10 note: WSL2 there is NAT-only (no loopback sharing), so WSL must
// reach the host over the network — exposure is required for the WSL split on
// Win10. On Windows 11 with WSL "mirrored networking", loopback is shared, so
// the split can work with exposure OFF.
#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InferenceExpose {
    /// false (default) → bind 127.0.0.1. true → bind 0.0.0.0 + require api_key.
    pub enabled: bool,
    /// Bearer key remote agents must send. Generated by the UI (crypto) when
    /// the user turns exposure on; required when enabled.
    #[serde(default)]
    pub api_key: String,
}

impl Default for InferenceExpose {
    fn default() -> Self { Self { enabled: false, api_key: String::new() } }
}

fn inference_expose_path() -> Option<std::path::PathBuf> {
    paths::user_data_root().map(|d| d.join("inference_expose.json"))
}

fn load_inference_expose() -> InferenceExpose {
    inference_expose_path()
        .and_then(|p| std::fs::read_to_string(&p).ok())
        .and_then(|s| serde_json::from_str::<InferenceExpose>(&s).ok())
        .unwrap_or_default()
}

#[tauri::command]
pub fn inference_expose_get() -> InferenceExpose {
    load_inference_expose()
}

#[tauri::command]
pub fn inference_expose_set(config: InferenceExpose) -> Result<InferenceExpose, String> {
    // Never allow unauthenticated network exposure.
    if config.enabled && config.api_key.trim().is_empty() {
        return Err("an API key is required to expose inference on the network".to_string());
    }
    let path = inference_expose_path().ok_or_else(|| "user data dir not found".to_string())?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    let json = serde_json::to_string_pretty(&config).map_err(|e| format!("serialize: {e}"))?;
    std::fs::write(&path, json).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(config)
}

#[derive(Default)]
pub struct ServerState {
    inner: Mutex<Inner>,
}

#[derive(Default)]
struct Inner {
    child: Option<Child>,
    model_id: Option<String>,
    port: Option<u16>,
    message: String,
    /// Rolling tail of the child's stderr — shared with the reader task.
    /// On crash, server_status classifies the cause from here (OOM vs
    /// broken GGUF vs other) far more precisely than the exit code alone.
    stderr_tail: Option<std::sync::Arc<std::sync::Mutex<Vec<String>>>>,
    /// True when this instance is REUSING a llama-server that another OwLLM
    /// instance (or a survivor of a prior run) already had live on the model's
    /// port — `child` is None because we don't own the process. Lets many
    /// instances share one model server instead of fighting over the port.
    adopted: bool,
}

/// Is a llama-server reachable on this loopback port right now? True when the
/// /health endpoint answers AT ALL (200 ready, or 503 still-loading, or even a
/// 401 when network-exposed): any HTTP reply means a server already owns this
/// port, so we adopt it rather than spawn a second one that can't bind. A
/// connection refusal / timeout means nothing is there. Kept short (1.5s) so a
/// dead port doesn't stall a start.
async fn server_present(port: u16) -> bool {
    let url = format!("http://127.0.0.1:{port}/health");
    match reqwest::Client::builder()
        .timeout(std::time::Duration::from_millis(1500))
        .build()
    {
        Ok(c) => c.get(&url).send().await.is_ok(),
        Err(_) => false,
    }
}

/// Classify a llama-server crash from its stderr tail. Returns the named
/// cause + remediation, or None when the output matches nothing known.
/// Patterns gathered from real llama.cpp failures (CUDA + Vulkan builds).
fn classify_crash(stderr_tail: &str) -> Option<(&'static str, &'static str)> {
    let t = stderr_tail.to_lowercase();
    // GPU/host memory exhaustion — the model (or its KV cache) didn't fit.
    if t.contains("out of memory")
        || t.contains("outofdevicememory")
        || t.contains("cudamalloc failed")
        || t.contains("cuda_malloc")
        || t.contains("failed to allocate")
        || t.contains("not enough memory")
        || t.contains("erroroutofdevicememory")
    {
        return Some((
            "oom",
            "The model didn't fit in memory (GPU/RAM OOM). Try a smaller quant (e.g. Q4_K_M), \
             fewer GPU layers, a smaller context size, or close other GPU apps.",
        ));
    }
    // Broken / incompatible model file.
    if t.contains("invalid magic")
        || t.contains("gguf_init_from_file")
        || t.contains("unknown model architecture")
        || t.contains("unknown architecture")
        || t.contains("error loading model")
        || t.contains("failed to load model")
        || t.contains("unsupported model")
        || t.contains("tensor") && t.contains("not found")
    {
        return Some((
            "bad_model",
            "The model file appears broken or incompatible with this llama.cpp build. \
             Re-download the GGUF (it may be truncated), or update the local-inference module \
             if the model is newer than the engine.",
        ));
    }
    None
}

#[tauri::command]
pub async fn server_status(state: tauri::State<'_, ServerState>) -> Result<ServerStatus, String> {
    let mut inner = state.inner.lock().await;
    // Adopted (shared) server: we hold no child, so liveness can only be told by
    // re-probing the port. If its owner instance closed, the server is gone —
    // clear the adoption so the UI stops claiming a model is running.
    if inner.child.is_none() && inner.adopted {
        let port = inner.port;
        let live = match port { Some(p) => server_present(p).await, None => false };
        if live {
            return Ok(ServerStatus {
                running: true,
                model_id: inner.model_id.clone(),
                port,
                message: inner.message.clone(),
            });
        }
        inner.adopted = false;
        inner.model_id = None;
        inner.port = None;
        inner.message = "The shared model server stopped (the OwLLM instance that owned it closed).".to_string();
        return Ok(ServerStatus { running: false, model_id: None, port: None, message: inner.message.clone() });
    }
    // Reap dead child so the "running" bit doesn't lie after a crash.
    let (alive, exit_code) = match inner.child.as_mut() {
        Some(c) => match c.try_wait() {
            Ok(None) => (true, None),
            Ok(Some(status)) => (false, status.code()),
            Err(_) => (false, None),
        },
        None => (false, None),
    };
    if !alive && inner.child.is_some() {
        // Transition from running -> dead: overwrite the stale
        // "Starting on http://..." message so the UI shows the truth.
        inner.child = None;
        // FIRST try to classify from what llama-server actually printed —
        // stderr names the cause (OOM vs broken GGUF) where the exit code
        // is ambiguous (both often die with the same NTSTATUS).
        let stderr_cause = inner
            .stderr_tail
            .as_ref()
            .and_then(|t| t.lock().ok().map(|v| v.join("\n")))
            .and_then(|tail| classify_crash(&tail).map(|(_, msg)| msg));
        inner.message = match (exit_code, stderr_cause) {
            (Some(0), _) => "Stopped cleanly.".to_string(),
            (code, Some(cause)) => format!(
                "Crashed{}. {cause} See log for the full trace.",
                code.map(|c| format!(" (exit code {c})")).unwrap_or_default()
            ),
            // Decode Windows NTSTATUS-style codes that surface as
            // signed i32 from Tokio's exit_status — these are by far
            // the most common llama-server crashes the user hits and
            // a bare exit code is impossible to act on without
            // googling. We surface the friendly cause + remediation
            // inline so the user knows the next step.
            (Some(code), None) => {
                let hint = crash_hint_for(code);
                if let Some(h) = hint {
                    format!("Crashed (exit code {code}). {h} See log for full trace.")
                } else {
                    format!("Crashed (exit code {code}). Check the log for details.")
                }
            }
            (None, None) => "Process ended unexpectedly. Check the log for details.".to_string(),
        };
    } else if !alive && inner.message.is_empty() {
        inner.message = "Not running.".to_string();
    }
    Ok(ServerStatus {
        running: alive,
        model_id: inner.model_id.clone(),
        port: inner.port,
        message: inner.message.clone(),
    })
}

/// A local vision model keeps its multimodal projector in a sibling
/// `mmproj-*.gguf` next to the weights (the model scan skips these as standalone
/// models, mirroring HF's naming). llama-server needs it via `--mmproj` to
/// accept image input. Returns the first sibling mmproj GGUF, or None when the
/// model is text-only (or the projector wasn't downloaded).
fn find_sibling_mmproj(base_model: &str) -> Option<std::path::PathBuf> {
    let dir = std::path::Path::new(base_model).parent()?;
    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        let p = entry.path();
        let is_gguf = p.extension().map(|x| x.eq_ignore_ascii_case("gguf")).unwrap_or(false);
        if !is_gguf { continue; }
        if let Some(stem) = p.file_stem().and_then(|s| s.to_str()) {
            if stem.to_ascii_lowercase().starts_with("mmproj") {
                return Some(p);
            }
        }
    }
    None
}

#[tauri::command]
pub async fn server_start(
    app: AppHandle,
    model_id: String,
    state: tauri::State<'_, ServerState>,
) -> Result<(), String> {
    // Resolve model entry by id.
    let registry = models::list_models().await?;
    let entry = registry
        .into_iter()
        .find(|m| m.model_id == model_id)
        .ok_or_else(|| format!("unknown model_id: {model_id}"))?;
    let port = entry
        .port
        .ok_or_else(|| format!("model {model_id} has no port in config"))?;
    let base_model = entry
        .base_model
        .ok_or_else(|| format!("model {model_id} has no base_model path"))?;

    // The llama.cpp engine (llama-server) ships as the `local-inference`
    // module — it is NOT bundled. On a fresh machine a user can download a
    // model but have no engine to run it, which previously dead-ended with a
    // cryptic "llama-server.exe not found; set OWLLM_LLAMA_SERVER…". This is
    // the single choke point for every model run (chat / code / agentic /
    // server tab), so auto-install the engine here instead. Reuses the exact
    // installer the Modules wizard uses; status surfaces on the server-log.
    let exe = match paths::llama_server_exe() {
        Some(p) => p,
        None => {
            let _ = app.emit("server-log", ServerLogEvent {
                stream: "stdout".into(),
                line: "[supervisor] llama.cpp engine not installed — installing the Local Inference module now (one-time, ~download)…".into(),
            });
            let hw = crate::hardware::hardware_info().await.unwrap_or_default();
            let snap = crate::modules::HardwareSnapshot::from_probe(&hw);
            let mgr = app.state::<crate::modules::ModuleManager>();
            // SELF-HEAL: clear any prior local-inference record first. install()
            // skips re-download when the recorded version matches — even if a
            // previous attempt extracted an INCOMPLETE payload (e.g. a momentarily
            // broken/cached download with no llama-server.exe). Without this, a
            // single bad download poisons the install permanently: every retry
            // "succeeds" (skipped) yet the binary is still missing. uninstall is
            // a no-op if nothing's recorded.
            let _ = mgr.inner().uninstall("local-inference");
            mgr.inner()
                .install(&app, "local-inference", &snap)
                .await
                .map_err(|e| {
                    format!("no inference engine and auto-install failed: {e}.")
                })?;
            let _ = app.emit("server-log", ServerLogEvent {
                stream: "stdout".into(),
                line: "[supervisor] Local Inference engine installed — starting the model…".into(),
            });
            paths::llama_server_exe().ok_or_else(|| {
                let name = paths::llama_server_filename();
                format!(
                    "{name} still missing after installing the engine — the module \
                     download may have failed. Check your internet connection and try again."
                )
            })?
        }
    };

    // Take the lock and stop any running child before spawning a new one.
    let mut inner = state.inner.lock().await;
    // Release a server WE own first (a restart / model switch). Remember its
    // port so we don't mistake our own just-killed socket for an adoptable one.
    let just_killed_port = if let Some(mut c) = inner.child.take() {
        let kp = inner.port;
        let _ = c.kill().await;
        inner.adopted = false;
        kp
    } else {
        None
    };
    // ADOPT-don't-spawn: if a llama-server is ALREADY live on this model's port
    // (another OwLLM instance, or a survivor of a prior run) and it isn't the
    // socket we just killed, reuse it. Spawning a second one would only fail to
    // bind the port and crash — which is exactly the "llama server gives errors"
    // collision. Sharing one server is what lets several instances coexist.
    if just_killed_port != Some(port) && server_present(port).await {
        inner.adopted = true;
        inner.model_id = Some(model_id.clone());
        inner.port = Some(port);
        inner.message = format!("Using the model server already running on :{port} (shared with another OwLLM instance).");
        drop(inner);
        let _ = app.emit("server-log", ServerLogEvent {
            stream: "stdout".into(),
            line: format!("[supervisor] adopted the model server already live on :{port} — not spawning a second one"),
        });
        let _ = app.emit("llama-ready", serde_json::json!({
            "model_id": model_id,
            "port": port,
            "elapsed_ms": 0,
        }));
        return Ok(());
    }
    inner.adopted = false;

    // Bind loopback by default; only open on the network when the user has
    // explicitly enabled exposure (which also forces an api-key). 0.0.0.0
    // still includes loopback, so the local /health poll + local UI keep
    // working when exposed.
    let expose = load_inference_expose();
    let exposed = expose.enabled && !expose.api_key.trim().is_empty();
    let expose_key = if exposed { expose.api_key.trim().to_string() } else { String::new() };

    let mut cmd = Command::new(&exe);
    cmd.arg("--model").arg(&base_model);
    cmd.arg("--host").arg(if exposed { "0.0.0.0" } else { "127.0.0.1" });
    cmd.arg("--port").arg(port.to_string());
    if exposed {
        cmd.arg("--api-key").arg(&expose_key);
    }
    // `-fit off` disables llama.cpp's auto-fit pass, which routinely
    // crashes with GGML_ASSERT(n_inputs < GGML_SCHED_MAX_SPLIT_INPUTS)
    // on models the heuristic can't place (verified on supergemma4 +
    // gemma-4-E4B in this tree). Pair with `-ngl 99` so all layers
    // go to GPU explicitly — without -ngl, `-fit off` defaults to
    // CPU and the user sees zero VRAM use, which feels like the app
    // is faking it. 99 is the conventional "all layers" sentinel.
    cmd.arg("-fit").arg("off");
    cmd.arg("-ngl").arg("99");
    // --jinja activates llama.cpp's jinja chat-template engine. WITHOUT
    // this flag, llama-server uses its built-in template fallback which
    // SILENTLY ignores `tools=[…]` on the request body AND can't parse
    // the model's native tool_call special tokens (`<|tool_call|>` etc.)
    // back into structured `delta.tool_calls`. The model still emits
    // those tokens because it was trained to, but they leak through as
    // raw `delta.content` text and the user sees hallucinated tool
    // exchanges in their reply. With --jinja, llama.cpp uses the GGUF's
    // bundled chat template which handles both directions properly for
    // every modern tool-calling model (Llama 3.1+, Qwen 2.5+, Gemma 3,
    // Hermes 3, Mistral Nemo+). Older models without a jinja template
    // fall back to the same built-in path as before — no regression.
    cmd.arg("--jinja");
    // Vision models keep their multimodal projector in a SIBLING `mmproj-*.gguf`
    // (the model scan deliberately skips those as standalone models). Without
    // `--mmproj`, llama-server loads text-only and rejects an image with
    // `500 image input is not supported - provide the mmproj` — the exact
    // failure when pasting a picture into a local gemma-3/4-style model. Pass it
    // when present so local vision input just works.
    if let Some(mmproj) = find_sibling_mmproj(&base_model) {
        cmd.arg("--mmproj").arg(&mmproj);
        let _ = app.emit("server-log", ServerLogEvent {
            stream: "stdout".into(),
            line: format!("[supervisor] vision projector found — loading --mmproj {}", mmproj.display()),
        });
    }
    // Pin inference to the GPU(s) the user picked in gpu_config.json.
    // Without this, llama.cpp's default split-mode=layer spreads the model
    // across EVERY visible GPU, so a 4090-only selection still lit up the
    // A2000 (the "using the A2000 all of a sudden" report).
    apply_gpu_selection(&mut cmd, &exe);
    cmd.stdin(Stdio::null());
    cmd.stdout(Stdio::piped());
    cmd.stderr(Stdio::piped());
    // NOT kill_on_drop: a detached/shared server must SURVIVE the window that
    // spawned it closing, so other windows keep using it. It's reaped by name
    // only when the LAST window closes (lib.rs close/exit hooks) or as a
    // startup orphan — both gated on the window registry.
    cmd.kill_on_drop(false);
    #[cfg(windows)]
    {
        // CREATE_NO_WINDOW — the whole reason we did the Python wipe.
        cmd.creation_flags(0x08000000);
    }

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("spawn {}: {e}", exe.display()))?;

    // Forward stdout + stderr to a Tauri event channel.
    if let Some(stdout) = child.stdout.take() {
        let app = app.clone();
        tokio::spawn(async move {
            let mut lines = BufReader::new(stdout).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                let _ = app.emit(
                    "server-log",
                    ServerLogEvent {
                        stream: "stdout".into(),
                        line,
                    },
                );
            }
        });
    }
    let stderr_tail = std::sync::Arc::new(std::sync::Mutex::new(Vec::<String>::new()));
    if let Some(stderr) = child.stderr.take() {
        let app = app.clone();
        let tail = stderr_tail.clone();
        tokio::spawn(async move {
            let mut lines = BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                // Keep a rolling tail so a crash can be classified (OOM vs
                // broken GGUF) from what llama-server actually said.
                if let Ok(mut t) = tail.lock() {
                    t.push(line.clone());
                    if t.len() > 120 {
                        t.remove(0);
                    }
                }
                let _ = app.emit(
                    "server-log",
                    ServerLogEvent {
                        stream: "stderr".into(),
                        line,
                    },
                );
            }
        });
    }

    inner.stderr_tail = Some(stderr_tail);
    inner.child = Some(child);
    inner.model_id = Some(model_id.clone());
    inner.port = Some(port);
    inner.message = format!("Starting on http://127.0.0.1:{port}");
    drop(inner);

    // Inform the UI immediately so the row turns "starting" without
    // waiting for a status poll.
    let _ = app.emit(
        "server-log",
        ServerLogEvent {
            stream: "stdout".into(),
            line: format!("[supervisor] spawned {} on :{port}", exe.display()),
        },
    );

    // Poll llama-server's /health every 500 ms until it flips from
    // 503 (still loading) to 200 (model resident in VRAM). On first
    // 200 emit `llama-ready` so the UI's Load button can flip to Send
    // deterministically instead of guessing with a 5-second timer.
    // The poll task self-terminates after first success or after
    // 10 min of consecutive failure (model too large / spawn died).
    {
        let app = app.clone();
        let ready_model = model_id.clone();
        // When exposed with an api-key, /health may require it too — send it.
        let health_key = expose_key.clone();
        tokio::spawn(async move {
            let url = format!("http://127.0.0.1:{port}/health");
            let client = match reqwest::Client::builder()
                .timeout(std::time::Duration::from_millis(800))
                .build()
            {
                Ok(c) => c,
                Err(_) => return,
            };
            let started = std::time::Instant::now();
            let deadline = std::time::Duration::from_secs(600);
            loop {
                if started.elapsed() > deadline {
                    let _ = app.emit(
                        "server-log",
                        ServerLogEvent {
                            stream: "stderr".into(),
                            line: format!(
                                "[supervisor] /health poll gave up after {}s",
                                started.elapsed().as_secs()
                            ),
                        },
                    );
                    return;
                }
                let mut req = client.get(&url);
                if !health_key.is_empty() { req = req.bearer_auth(&health_key); }
                match req.send().await {
                    Ok(resp) if resp.status().as_u16() == 200 => {
                        let elapsed_ms = started.elapsed().as_millis() as u64;
                        let _ = app.emit(
                            "server-log",
                            ServerLogEvent {
                                stream: "stdout".into(),
                                line: format!(
                                    "[supervisor] model ready in {} ms",
                                    elapsed_ms
                                ),
                            },
                        );
                        let _ = app.emit(
                            "llama-ready",
                            serde_json::json!({
                                "model_id": ready_model,
                                "port": port,
                                "elapsed_ms": elapsed_ms,
                            }),
                        );
                        return;
                    }
                    _ => {
                        tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                    }
                }
            }
        });
    }

    Ok(())
}

#[tauri::command]
pub async fn server_stop(
    app: AppHandle,
    state: tauri::State<'_, ServerState>,
) -> Result<(), String> {
    let mut inner = state.inner.lock().await;
    // An ADOPTED server belongs to another instance — we only stop USING it; we
    // must NOT kill it out from under the instances still relying on it.
    if inner.adopted {
        inner.adopted = false;
        inner.model_id = None;
        inner.port = None;
        inner.message = "Released the shared server (it stays up for other OwLLM instances).".to_string();
        drop(inner);
        let _ = app.emit(
            "server-log",
            ServerLogEvent { stream: "stdout".into(), line: "[supervisor] released the shared model server (not owned by this instance)".into() },
        );
        return Ok(());
    }
    if let Some(mut c) = inner.child.take() {
        let _ = c.kill().await;
    }
    inner.model_id = None;
    inner.port = None;
    inner.message = "Stopped.".to_string();
    drop(inner);
    let _ = app.emit(
        "server-log",
        ServerLogEvent {
            stream: "stdout".into(),
            line: "[supervisor] server stopped".into(),
        },
    );
    Ok(())
}

/// Restrict the spawned llama-server to ONLY the GPU(s) the user selected
/// in gpu_config.json. We pin by STABLE identifiers, never the persisted
/// index — nvidia-smi, CUDA and Vulkan all number GPUs differently (on the
/// dev box the 4090 is nvidia-smi index 1 but Vulkan index 0, so reusing
/// the stored index would pin to the WRONG card). No selection → leave the
/// backend default untouched.
fn apply_gpu_selection(cmd: &mut Command, exe: &std::path::Path) {
    let uuids = crate::hardware::selected_gpu_uuids();
    if uuids.is_empty() {
        return;
    }
    let path_lc = exe.to_string_lossy().to_lowercase();

    // CUDA build: CUDA_VISIBLE_DEVICES accepts GPU UUIDs directly, so this
    // is ordering-independent — no PCI_BUS_ID dance needed.
    if path_lc.contains("cuda") {
        cmd.env("CUDA_VISIBLE_DEVICES", uuids.join(","));
        return;
    }

    // Vulkan build (the shipped default): resolve each selected UUID to its
    // nvidia-smi NAME, then match that name against `--list-devices` to get
    // the Vulkan device index. GGML_VK_VISIBLE_DEVICES hides every other
    // GPU so llama.cpp can only use the chosen one(s).
    if path_lc.contains("vulkan") {
        // One name per SELECTED uuid (duplicates kept). Vulkan's
        // --list-devices exposes only name+memory — no UUID/PCI — so for
        // IDENTICAL cards we can't bind a specific physical one, but we
        // honour the exact COUNT the user picked (select 2 of 4 4090s →
        // exactly 2 Vulkan 4090s, not all 4). For distinct cards the name
        // uniquely identifies the device, so selection is exact.
        let names = crate::hardware::gpu_names_for_uuids(&uuids);
        if names.is_empty() {
            return;
        }
        let mut want: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
        for n in &names {
            *want.entry(n.trim().to_lowercase()).or_insert(0) += 1;
        }
        let mut idxs: Vec<String> = Vec::new();
        for (idx, vk_name) in list_vulkan_devices(exe) {
            // Consume one budget slot for the first selected name this
            // Vulkan device matches — so we take exactly `count` of each.
            let key = want
                .iter()
                .find(|(k, c)| **c > 0 && gpu_name_matches(k, &vk_name))
                .map(|(k, _)| k.clone());
            if let Some(k) = key {
                *want.get_mut(&k).unwrap() -= 1;
                idxs.push(idx.to_string());
            }
        }
        if !idxs.is_empty() {
            cmd.env("GGML_VK_VISIBLE_DEVICES", idxs.join(","));
        }
    }
}

/// Loose GPU-name match (nvidia-smi vs Vulkan can phrase a name slightly
/// differently). Case-insensitive equality or containment either way.
fn gpu_name_matches(a: &str, b: &str) -> bool {
    let (na, nb) = (a.trim().to_lowercase(), b.trim().to_lowercase());
    !na.is_empty() && (na == nb || na.contains(&nb) || nb.contains(&na))
}

/// Run `llama-server --list-devices` and parse its
/// "VulkanN: <name> (<mem>)" lines into (index, name) pairs.
fn list_vulkan_devices(exe: &std::path::Path) -> Vec<(u32, String)> {
    let mut c = std::process::Command::new(exe);
    c.arg("--list-devices");
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        c.creation_flags(0x08000000);
    }
    let Ok(out) = c.output() else { return Vec::new(); };
    let text = String::from_utf8_lossy(&out.stdout);
    let mut devs = Vec::new();
    for line in text.lines() {
        let l = line.trim();
        let Some(rest) = l.strip_prefix("Vulkan") else { continue };
        let Some(colon) = rest.find(':') else { continue };
        let Ok(idx) = rest[..colon].parse::<u32>() else { continue };
        let after = rest[colon + 1..].trim();
        let name = after.split('(').next().unwrap_or(after).trim().to_string();
        if !name.is_empty() {
            devs.push((idx, name));
        }
    }
    devs
}

/// Translate the most common llama-server crash exit codes into a
/// one-line, actionable English hint shown alongside the raw number
/// in the Server tab status. Built around what the user actually
/// hits on Windows; non-matches fall through to the generic
/// "Check the log for details." message.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_cuda_oom() {
        // Real llama.cpp CUDA OOM shape.
        let tail = "ggml_backend_cuda_buffer_type_alloc_buffer: allocating 23028.00 MiB on device 0: cudaMalloc failed: out of memory\nllama_model_load: error loading model: unable to allocate CUDA0 buffer";
        let (kind, msg) = classify_crash(tail).expect("classified");
        assert_eq!(kind, "oom");
        assert!(msg.contains("smaller quant"));
    }

    #[test]
    fn classifies_vulkan_oom() {
        let tail = "ggml_vulkan: Device memory allocation of size 18253611008 failed.\nggml_vulkan: vk::Device::allocateMemory: ErrorOutOfDeviceMemory";
        let (kind, _) = classify_crash(tail).expect("classified");
        assert_eq!(kind, "oom");
    }

    #[test]
    fn classifies_broken_gguf() {
        // Real llama.cpp corrupt-file shape.
        let tail = "gguf_init_from_file: invalid magic characters 'Junk'\nllama_model_load: error loading model: llama_model_loader: failed to load model from C:\\models\\broken.gguf";
        let (kind, msg) = classify_crash(tail).expect("classified");
        assert_eq!(kind, "bad_model");
        assert!(msg.contains("Re-download"));
    }

    #[test]
    fn classifies_unknown_architecture() {
        let tail = "llama_model_load: error loading model: unknown model architecture: 'qwen3next'";
        let (kind, _) = classify_crash(tail).expect("classified");
        assert_eq!(kind, "bad_model");
    }

    #[test]
    fn clean_log_classifies_as_none() {
        let tail = "llama_new_context_with_model: graph splits = 2\nmain: server is listening on http://127.0.0.1:8080";
        assert!(classify_crash(tail).is_none());
    }

    /// Live probe (needs the local-inference module installed): feed the REAL
    /// llama-server a deliberately corrupt GGUF, capture its stderr, and
    /// assert the classifier names it. Run:
    ///   cargo test --lib -- --ignored --nocapture probe_broken_gguf
    #[test]
    #[ignore]
    fn probe_broken_gguf_named_by_classifier() {
        let exe = crate::paths::llama_server_exe().expect("llama-server installed");
        let dir = std::env::temp_dir().join("owllm_p14_probe");
        std::fs::create_dir_all(&dir).unwrap();
        let bad = dir.join("broken.gguf");
        std::fs::write(&bad, b"Junk_this_is_not_a_gguf_file_____").unwrap();
        let mut cmd = std::process::Command::new(&exe);
        cmd.arg("-m").arg(&bad).arg("--port").arg("18181");
        cmd.stdout(std::process::Stdio::piped()).stderr(std::process::Stdio::piped());
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            cmd.creation_flags(0x08000000);
        }
        let out = cmd.output().expect("spawn llama-server");
        let stderr = String::from_utf8_lossy(&out.stderr);
        let merged = format!("{}\n{}", String::from_utf8_lossy(&out.stdout), stderr);
        eprintln!("== llama-server said ==\n{}", merged.trim());
        assert!(!out.status.success(), "corrupt gguf should not start");
        let (kind, msg) = classify_crash(&merged).expect("crash classified");
        eprintln!("== classified: {kind} — {msg}");
        assert_eq!(kind, "bad_model");
    }
}

fn crash_hint_for(code: i32) -> Option<&'static str> {
    // Tokio's exit_status returns the unsigned NTSTATUS as a signed
    // i32, so 0xC000_0005 surfaces as -1_073_741_819, etc. Match on
    // both forms for clarity.
    let unsigned = code as u32;
    match unsigned {
        0xC000_0005 => Some(
            "STATUS_ACCESS_VIOLATION — usually VRAM OOM on a too-large model. \
             Try a smaller quant (e.g. Q4_K_M instead of f16) or lower -ngl."
        ),
        0xC000_0017 => Some(
            "STATUS_NO_MEMORY — out of system RAM. Close other apps or pick a smaller model."
        ),
        0xC000_001D => Some(
            "STATUS_ILLEGAL_INSTRUCTION — the llama.cpp build needs a CPU feature this machine lacks. \
             Reinstall the llama.cpp runtime with the non-AVX build."
        ),
        0xC000_0096 => Some(
            "STATUS_PRIVILEGED_INSTRUCTION — same root cause as STATUS_ILLEGAL_INSTRUCTION: CPU/build mismatch."
        ),
        0xC000_0142 => Some(
            "STATUS_DLL_INIT_FAILED — a CUDA / cuBLAS DLL failed to load. \
             Reinstall the llama.cpp+CUDA runtime."
        ),
        0xC000_0409 => Some(
            "STATUS_STACK_BUFFER_OVERRUN — likely a corrupt model file. Re-download or re-export the GGUF."
        ),
        _ => None,
    }
}

/// Convenience: install ServerState in a Tauri builder. Keeps the
/// `.manage(ServerState::default())` call out of lib.rs's wiring
/// manifest — module-local concerns stay in the module.
///
/// Also kills any leftover llama-server processes from a previous
/// session. The user has been bitten by this: kill_on_drop(true) on
/// tokio's Command isn't guaranteed to fire if the app is
/// force-killed, panics during shutdown, or the OS reaps the parent
/// before drop runs. Wiping orphans at startup gives the user a
/// reliably-clean slate every launch — and matches the UI's
/// expectation (header says "Stopped" the moment the app starts).
pub fn install<R: tauri::Runtime>(app: &tauri::App<R>) {
    app.manage(ServerState::default());
    // Multi-window lifecycle: count THIS window in the shared registry, then
    // only wipe a leftover llama-server when we're the ONLY window. If another
    // OwLLM window is live it's SHARING that server (multi-instance) — nuking it
    // on our startup is exactly what broke "open a second window". A server
    // still running with zero live windows is a crash-orphan → reap it so the
    // GPU is never stranded and the header honestly reads "Stopped".
    register_window();
    if other_live_windows() == 0 {
        kill_all_llama_servers("startup-orphan-reap");
    }
    // Heartbeat so this window stays "live" while open; a crashed window's entry
    // just expires (WINDOW_TTL_SECS) so it stops blocking the last-window reap.
    tauri::async_runtime::spawn(async {
        loop {
            tokio::time::sleep(std::time::Duration::from_secs(10)).await;
            register_window();
        }
    });
}

// --- Window registry: reference-count OwLLM windows ACROSS processes so the
// shared (detached) llama-server is reaped only when the LAST window closes, and
// a crash-orphaned server is reaped on next launch — the GPU is never stranded.
// Keyed by OS process id; a 10s heartbeat keeps each entry fresh, a 30s TTL
// expires a crashed window's stale entry. Best-effort: any IO failure degrades
// to "I'm the only window", i.e. the safe (reap) behaviour.
const WINDOW_TTL_SECS: u64 = 30;
fn windows_registry_path() -> Option<std::path::PathBuf> {
    Some(crate::paths::owllm_config_home()?.join("owllm_windows.json"))
}
fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}
fn load_windows() -> std::collections::HashMap<String, u64> {
    let Some(p) = windows_registry_path() else { return Default::default(); };
    if !p.is_file() { return Default::default(); }
    std::fs::read_to_string(&p)
        .ok()
        .and_then(|r| serde_json::from_str(&r).ok())
        .unwrap_or_default()
}
fn save_windows(m: &std::collections::HashMap<String, u64>) {
    let Some(p) = windows_registry_path() else { return; };
    if let Some(parent) = p.parent() { let _ = std::fs::create_dir_all(parent); }
    if let Ok(json) = serde_json::to_string_pretty(m) { let _ = std::fs::write(&p, json); }
}
fn prune_windows(m: &mut std::collections::HashMap<String, u64>) {
    let now = now_secs();
    m.retain(|_, ts| now.saturating_sub(*ts) <= WINDOW_TTL_SECS);
}
/// Record THIS process as a live window (also the heartbeat tick).
pub fn register_window() {
    let mut m = load_windows();
    prune_windows(&mut m);
    m.insert(std::process::id().to_string(), now_secs());
    save_windows(&m);
}
/// Remove THIS process from the live set (on window close / app exit).
pub fn deregister_window() {
    let mut m = load_windows();
    m.remove(&std::process::id().to_string());
    prune_windows(&mut m);
    save_windows(&m);
}
/// How many OTHER OwLLM windows are live right now (fresh heartbeat, not us).
pub fn other_live_windows() -> usize {
    let me = std::process::id().to_string();
    let mut m = load_windows();
    prune_windows(&mut m);
    m.keys().filter(|k| **k != me).count()
}

/// Walk the OS process table and kill every llama-server process by
/// name. Idempotent — safe to call multiple times. Called on
/// startup AND on app-exit so the user never accumulates orphans.
///
/// The `reason` string is just for the eprintln so we can see in the
/// log which path triggered the cleanup.
pub fn kill_all_llama_servers(reason: &str) {
    use sysinfo::System;
    let target_lc = if cfg!(windows) { "llama-server.exe" } else { "llama-server" };
    let mut sys = System::new();
    sys.refresh_processes(sysinfo::ProcessesToUpdate::All, true);
    let mut killed = 0usize;
    for process in sys.processes().values() {
        let name = process.name().to_string_lossy();
        if name.eq_ignore_ascii_case(target_lc) {
            if process.kill() {
                killed += 1;
            }
        }
    }
    if killed > 0 {
        eprintln!("[supervisor] {reason}: killed {killed} stray llama-server process(es)");
    }
}
